apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-backend
  template:
    metadata:
      labels:
        app: devops-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: backend-container
          image: ghcr.io/belinracle/itmo-devops/devops-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: tg-secrets
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://devops-postgres:5432/postgres_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres_user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres_password"
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"