apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  labels:
    release: kube-prometheus-stack  # ← Изменили здесь
spec:
  jobLabel: devops-backend
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
      params:
        Accept: [ "text/plain" ]  # для обхода 406
  selector:
    matchLabels:
      app: devops-backend
  namespaceSelector:
    any: true