---
# Deployment для Backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-backend
  template:
    metadata:
      labels:
        app: devops-backend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: devops-backend
          image: ghcr.io/belinracle/itmo-devops/devops-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
---
# Service для Backend
apiVersion: v1
kind: Service
metadata:
  name: devops-backend-service
spec:
  type: NodePort
  selector:
    app: devops-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
---
# Deployment для Frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-frontend
  template:
    metadata:
      labels:
        app: devops-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: devops-frontend
          image: ghcr.io/belinracle/itmo-devops/devops-frontend:latest
          ports:
            - containerPort: 3000  # Исправлено на 3000
          env:
            - name: VITE_BACKEND_URL
              value: "http://devops-backend-service:8080"
---
# Service для Frontend
apiVersion: v1
kind: Service
metadata:
  name: devops-frontend-service
spec:
  type: NodePort
  selector:
    app: devops-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000   # Исправлено на 3000
      nodePort: 30080