services:
  backend:
    build:
      context: backend
    depends_on:
      - database
    ports:
      - "8080:8080"
  frontend:
    build:
      context: frontend
      args:
        VITE_BACKEND_URL: http://localhost:8080
    depends_on:
      - backend
    ports:
      - "3000:3000"
  database:
    image: postgres:14.17-alpine
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata