apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-backend-monitor
  namespace: default
spec:
  jobLabel: devops-backend
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 10s
  selector:
    matchLabels:
      app: devops-backend
  namespaceSelector:
    any: true