server:
  port: 80

spring:
  application:
    name: rjp-backend
  datasource:
    url: jdbc:mysql://localhost:3306/product_management
    username: root
    password: Mysql@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true