server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application:
        name: ${spring.application.name}
  health:
    liveness:
      enabled: true
    readiness:
      enabled: true

spring:
  application:
    name: devops-backend
  datasource:
    url: jdbc:postgresql://database:5432/postgres_db
    username: postgres_user
    password: postgres_password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

tg:
  botToken: ${TG_BOT_TOKEN}
  chatId: ${TG_CHAT_ID}