name: CI Build
on:
  push:
    branches:
      - '**'
jobs:
  backendBuild:
    name: Backend Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        working-directory: ./backend
        run: mvn compile
  frontendBuild:
    name: Frontend Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
  frontendTestAndSonar:
    name: Frontend Test and Sonar Analysis
    runs-on: ubuntu-latest
    needs: [ frontendBuild ]
    defaults:
      run:
        working-directory: ./frontend
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Run tests and generate coverage report
        run: npm run coverage

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-frontend
          restore-keys: ${{ runner.os }}-sonar-frontend

      - name: Run SonarQube Analysis
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: ./frontend
          args: >
            -Dsonar.host.url=https://ad-capital.ru:62207
            -Dsonar.projectName=devops_frontend
            -Dsonar.projectKey=devops_frontend
            -Dsonar.ssl.verificationMode=NONE
            -Dsonar.source.encoding=UTF-8
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.test.inclusions=**/*.test.*
            -Dsonar.coverage.exclusions=src/main.jsx,src/App.jsx
            -Dsonar.qualitygate.wait=true
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
  backendTestAndSonar:
    name: Backend Test and Sonar Analysis
    runs-on: ubuntu-latest
    env:
      TG_BOT_TOKEN: 'test'
      TG_CHAT_ID: 'test'
    needs: [ backendBuild ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Build project + run tests + coverage check
        working-directory: ./backend
        run: |
          # Создаём нужную директорию явно
          mkdir -p target/coverage-reports

          # Запускаем тесты и проверяем покрытие
          mvn clean verify

          # Проверяем, что jacoco.exec создан
          ls -la target/coverage-reports/jacoco.exec

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Run SonarQube analysis
        working-directory: ./backend
        run: |
          mvn sonar:sonar -Dmaven.wagon.http.ssl.insecure=true \
            -Dmaven.wagon.http.ssl.allowall=true \
            -Dmaven.wagon.http.ssl.ignore.validity.dates=true \
            -Djavax.net.ssl.trustStore=/dev/null \
            -Djavax.net.ssl.trustStorePassword= \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.host.url=https://ad-capital.ru:62207  \
            -Dsonar.source.encoding=UTF-8 \
            -Dsonar.java.binaries=target/classes \
            -Dsonar.junit.reportsPath=target/surefire-reports \
            -Dsonar.coverage.jacoco.reportPaths=target/site/jacoco/report/jacoco.xml \
            -Dsonar.qualitygate.wait=true
        continue-on-error: false
  dockerBuildAndPush:
    name: Build and Push to GitHub Container Registry
    runs-on: ubuntu-latest
    needs: [ backendTestAndSonar, frontendTestAndSonar ]
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/belinracle/itmo-devops/devops-backend:${{ github.sha }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/belinracle/itmo-devops/devops-frontend:${{ github.sha }}

  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest
    needs: [ dockerBuildAndPush ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        env:
          GIT_SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.SERVER_IP }}
          port: 57609
          username: daniel
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/daniel/devops/itmo-devops
            git pull origin master
  
            # Вариант 1: через kubectl set image
            kubectl set image deployment/devops-backend backend-container=ghcr.io/belinracle/itmo-devops/devops-backend:${{ github.sha }}
            kubectl set image deployment/devops-frontend devops-frontend=ghcr.io/belinracle/itmo-devops/devops-frontend:${{ github.sha }}
  
            # Вариант 2: через envsubst (закомментируй предыдущий блок и раскомментируй этот):
            # envsubst < k8s/backend/deployment.yaml | kubectl apply -f -
            # envsubst < k8s/frontend/deployment.yaml | kubectl apply -f -
  
            kubectl rollout status deployment/devops-backend
            kubectl rollout status deployment/devops-frontend