name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build Docker images and Deploy to Kubernetes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/belinracle/itmo-devops/devops-backend:latest

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/belinracle/itmo-devops/devops-frontend:latest

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure KUBECONFIG
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Verify connection to cluster
        run: |
          kubectl version --client
          kubectl cluster-info

      - name: Deploy app to Kubernetes
        run: |
          cd k8s
          kubectl apply -f backend/deployment.yaml
          kubectl apply -f frontend/deployment.yaml
          kubectl rollout restart deployment/devops-backend
          kubectl rollout restart deployment/devops-frontend
          kubectl rollout status deployment/devops-backend
          kubectl rollout status deployment/devops-frontend

      - name: Restart Prometheus if needed (опционально)
        run: |
          kubectl rollout restart statefulset/prometheus-kube-prometheus-stack-prometheus